[package]
name = "magic_static_macro"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
quote = "1"